"""adding the claim ORM

Revision ID: 2d4df08eecf7
Revises: 94ce75362c8f
Create Date: 2025-08-11 14:38:33.195086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4df08eecf7'
down_revision: Union[str, Sequence[str], None] = '94ce75362c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op: exclude SQLite FTS virtual/aux tables from migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op: exclude SQLite FTS virtual/aux tables from migration
    # ### end Alembic commands ###
