"""various game ORM changes

Revision ID: d3c21d25a673
Revises: 2d4df08eecf7
Create Date: 2025-08-12 04:07:37.165628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c21d25a673'
down_revision: Union[str, Sequence[str], None] = '2d4df08eecf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_claim_buildings', schema=None) as batch_op:
        batch_op.alter_column('building_nickname', existing_type=sa.String(length=255), nullable=True)
    with op.batch_alter_table('game_claim_building_inventories', schema=None) as batch_op:
        batch_op.drop_column('item_id')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_claim_building_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=False))
    with op.batch_alter_table('game_claim_buildings', schema=None) as batch_op:
        batch_op.alter_column('building_nickname', existing_type=sa.String(length=255), nullable=False)

    # ### end Alembic commands ###
