services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      # Mount volume for SQLite database persistence only
      - api_data:/api/data
    environment:
      # OAuth redirect URLs for production
      - DISCORD_REDIRECT_URL=https://bitcraft.derp.tools/login
      - GOOGLE_REDIRECT_URL=https://bitcraft.derp.tools/login

      # File-based secrets (recommended approach)
      - DISCORD_CLIENT_ID_FILE=/run/secrets/discord_client_id
      - DISCORD_CLIENT_SECRET_FILE=/run/secrets/discord_client_secret
      - GOOGLE_CLIENT_ID_FILE=/run/secrets/google_client_id
      - GOOGLE_CLIENT_SECRET_FILE=/run/secrets/google_client_secret
      - JWT_SECRET_KEY_FILE=/run/secrets/jwt_secret_key

      # Logfire settings
      - LOGFIRE_TOKEN_FILE=/run/secrets/logfire_token
    secrets:
      - discord_client_id
      - discord_client_secret
      - jwt_secret_key
      - logfire_token
    networks:
      - bitcraft-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    expose:
      - "80"
    networks:
      - bitcraft-network
    depends_on:
      - api

# Docker secrets for secure credential management
secrets:
  discord_client_id:
    file: ./secrets/discord_client_id.txt
  discord_client_secret:
    file: ./secrets/discord_client_secret.txt
  jwt_secret_key:
    file: ./secrets/jwt_secret_key.txt
  logfire_token:
    file: ./secrets/logfire_token.txt

volumes:
  api_data:

networks:
  bitcraft-network:
    driver: bridge 